---
ioPaths:
  - - "ui/*.ui"
    - "src/main/python/plotlyst/view/generated/%%FILENAME%%_ui.py"
  - - "resources/*.qrc"
    - "src/main/python/plotlyst//view/generated/%%FILENAME%%_rc.py"
uic_options: --from-imports
force: False
