os: osx
osx_image:
  #- xcode12
  - xcode12.5
language: generic

install:
  - gem install --no-document fpm
  - python3 -m pip install --upgrade pip
  - python3 -m venv venv
  - source venv/bin/activate
  - python3 -V
  - pip3 install gdown
  - gdown $FBS_PROXY_URL -q -O fbs.tar.gz
  - pip3 install fbs.tar.gz
  - pip3 install pyqt5ac
  - pip3 install -e .

script:
  - pyqt5ac --config .pyqt5ac.yml
  - fbs freeze
  - fbs installer

deploy:
  provider: releases
  api_key: "$GITHUB_API_TOKEN"
  file: "target/Plotlyst.dmg"
  name: "Plotlyst-$TRAVIS_OSX_IMAGE.dmg"
  skip_cleanup: true
  draft: true
  on:
    branch: feature/travis
