os: osx
env:
  - MB_PYTHON_VERSION=3.7
language: generic

install:
  - git clone https://github.com/matthew-brett/multibuild.git
  - source multibuild/osx_utils.sh
  - python3 -m pip3 install --upgrade pip3
  - pip3 install gdown pyqt5ac
  - pip3 install -e .

script:
  - echo "hello"
