os: osx
language: generic

install:
  #- git clone https://github.com/matthew-brett/multibuild.git
  #- source multibuild/osx_utils.sh
  - python3 -m pip install --upgrade pip
  - python3 -m venv venv
  - source venv/bin/activate
  #- gem install --no-document fpm
  - python3 -V
  - pip3 install gdown pyqt5ac
  - gdown $FBS_PROXY_URL -q -O fbs.tar.gz
  - pip3 install fbs.tar.gz
  #- pip3 install -e .

script:
  - echo "hello"
