name: Build distributions with briefcase

on:
  push:
    branches: [ 'release/**' ]

jobs:
  build:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install beeware
          python -m pip install PyQt6==6.4.0 PyQt6-Qt6==6.4.0
          python -m pip install git+https://github.com/plotlyst/qt-uic.git
      - name: Generate code
        run: |
          qt-uic --source ui --target src/main/python/plotlyst/view/generated
      - name: Create with beeware
        run: |
          briefcase create
      - name: Package with beeware
        run: |
          briefcase build
          briefcase package
      - uses: actions/upload-artifact@v2
        with:
          name: plotlyst-app
          path: dist\Plotlyst-0.1.0.msi
      

