# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build distributions

on:
  push:
    branches: [ 'release/**' ]

jobs:
  Build_distribution:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-2016, macos-10.15 ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Add mask
        run: |
          echo "::add-mask::${{secrets.FBS_URL}}"
          echo "::add-mask::${{secrets.FBS_PROXY_URL}}"
          echo "::add-mask::${{secrets.FBS_URL_SHORTER}}"
          echo "::add-mask::${{secrets.MACOS_CERTIFICATE}}"
          echo "::add-mask::${{secrets.MACOS_CERTIFICATE_PWD}}"
          echo "::add-mask::${{secrets.KEYCHAIN_PWD}}"
          echo "::add-mask::${{secrets.NOTARIZATION_USERNAME}}"
          echo "::add-mask::${{secrets.NOTARIZATION_PASSWORD}}"
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.1

      - if: matrix.os == 'ubuntu-latest'
        name: Install fpm on Linux
        run: |
          sudo gem install --no-document fpm
      - if: matrix.os == 'macos-10.15'
        name: Install fpm on Mac
        run: |
          gem install --no-document fpm
      - if: matrix.os == 'windows-2016'
        name: Install fpm on Windows
        run: |
          gem install --no-document fpm

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gdown
          gdown ${{secrets.FBS_PROXY_URL}} -q -O fbs.tar.gz
          pip install fbs.tar.gz
          pip install -e .
      - name: Generate code
        run: |
          mkdir src/main/python/plotlyst/view/generated

          pyuic6 ui/about_dialog.ui -o src/main/python/plotlyst/view/generated/about_dialog_ui.py
          pyuic6 ui/avatar_widget.ui -o src/main/python/plotlyst/view/generated/avatar_widget_ui.py
          pyuic6 ui/backstory_editor_dialog.ui -o src/main/python/plotlyst/view/generated/backstory_editor_dialog_ui.py
          pyuic6 ui/cause_and_effect_editor.ui -o src/main/python/plotlyst/view/generated/cause_and_effect_editor_ui.py
          pyuic6 ui/character_backstory_card.ui -o src/main/python/plotlyst/view/generated/character_backstory_card_ui.py
          pyuic6 ui/character_card.ui -o src/main/python/plotlyst/view/generated/character_card_ui.py
          pyuic6 ui/character_conflict_widget.ui -o src/main/python/plotlyst/view/generated/character_conflict_widget_ui.py
          pyuic6 ui/character_editor.ui -o src/main/python/plotlyst/view/generated/character_editor_ui.py
          pyuic6 ui/character_profile_editor_dialog.ui -o src/main/python/plotlyst/view/generated/character_profile_editor_dialog_ui.py
          pyuic6 ui/characters_view.ui -o src/main/python/plotlyst/view/generated/characters_view_ui.py
          pyuic6 ui/comments_view.ui -o src/main/python/plotlyst/view/generated/comments_view_ui.py
          pyuic6 ui/comment_widget.ui -o src/main/python/plotlyst/view/generated/comment_widget_ui.py
          pyuic6 ui/directory_picker_dialog.ui -o src/main/python/plotlyst/view/generated/directory_picker_dialog_ui.py
          pyuic6 ui/docs_sidebar_widget.ui -o src/main/python/plotlyst/view/generated/docs_sidebar_widget_ui.py
          pyuic6 ui/field_text_selection_widget.ui -o src/main/python/plotlyst/view/generated/field_text_selection_widget_ui.py
          pyuic6 ui/home_view.ui -o src/main/python/plotlyst/view/generated/home_view_ui.py
          pyuic6 ui/icon_selector_widget.ui -o src/main/python/plotlyst/view/generated/icon_selector_widget_ui.py
          pyuic6 ui/items_editor_dialog.ui -o src/main/python/plotlyst/view/generated/items_editor_dialog_ui.py
          pyuic6 ui/items_editor_widget.ui -o src/main/python/plotlyst/view/generated/items_editor_widget_ui.py
          pyuic6 ui/journal_card.ui -o src/main/python/plotlyst/view/generated/journal_card_ui.py
          pyuic6 ui/journal_widget.ui -o src/main/python/plotlyst/view/generated/journal_widget_ui.py
          pyuic6 ui/locations_view.ui -o src/main/python/plotlyst/view/generated/locations_view_ui.py
          pyuic6 ui/main_window.ui -o src/main/python/plotlyst/view/generated/main_window_ui.py
          pyuic6 ui/manuscript_view.ui -o src/main/python/plotlyst/view/generated/manuscript_view_ui.py
          pyuic6 ui/notes_view.ui -o src/main/python/plotlyst/view/generated/notes_view_ui.py
          pyuic6 ui/novel_card.ui -o src/main/python/plotlyst/view/generated/novel_card_ui.py
          pyuic6 ui/novel_creation_dialog.ui -o src/main/python/plotlyst/view/generated/novel_creation_dialog_ui.py
          pyuic6 ui/novel_view.ui -o src/main/python/plotlyst/view/generated/novel_view_ui.py
          pyuic6 ui/plot_editor_dialog.ui -o src/main/python/plotlyst/view/generated/plot_editor_dialog_ui.py
          pyuic6 ui/reports_view.ui -o src/main/python/plotlyst/view/generated/reports_view_ui.py
          pyuic6 ui/scene_beat_item_widget.ui -o src/main/python/plotlyst/view/generated/scene_beat_item_widget_ui.py
          pyuic6 ui/scene_builder_preview_dialog.ui -o src/main/python/plotlyst/view/generated/scene_builder_preview_dialog_ui.py
          pyuic6 ui/scene_card.ui -o src/main/python/plotlyst/view/generated/scene_card_ui.py
          pyuic6 ui/scene_dstribution_widget.ui -o src/main/python/plotlyst/view/generated/scene_dstribution_widget_ui.py
          pyuic6 ui/scene_editor.ui -o src/main/python/plotlyst/view/generated/scene_editor_ui.py
          pyuic6 ui/scene_element_edition_dialog.ui -o src/main/python/plotlyst/view/generated/scene_element_edition_dialog_ui.py
          pyuic6 ui/scene_filter_widget.ui -o src/main/python/plotlyst/view/generated/scene_filter_widget_ui.py
          pyuic6 ui/scene_ouctome_selector.ui -o src/main/python/plotlyst/view/generated/scene_ouctome_selector_ui.py
          pyuic6 ui/scene_structure_editor_widget.ui -o src/main/python/plotlyst/view/generated/scene_structure_editor_widget_ui.py
          pyuic6 ui/scenes_view.ui -o src/main/python/plotlyst/view/generated/scenes_view_ui.py
          pyuic6 ui/sprint_widget.ui -o src/main/python/plotlyst/view/generated/sprint_widget_ui.py
          pyuic6 ui/tasks_widget.ui -o src/main/python/plotlyst/view/generated/tasks_widget_ui.py
          pyuic6 ui/timeline_view.ui -o src/main/python/plotlyst/view/generated/timeline_view_ui.py
          pyuic6 ui/timer_setup_widget.ui -o src/main/python/plotlyst/view/generated/timer_setup_widget_ui.py

      - name: fbs
        run: |
          fbs freeze

      - if: matrix.os == 'macos-10.15'
        name: Sign Macos App
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        run: |
          echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p ${{secrets.KEYCHAIN_PWD}} build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p ${{secrets.KEYCHAIN_PWD}} build.keychain
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k ${{secrets.KEYCHAIN_PWD}} build.keychain
          /usr/bin/codesign -v --timestamp --options=runtime --entitlements entitlements.plist --deep --force -s ${{secrets.MACOS_CERTIFICATE_IDENTITY}} target/Plotlyst.app

      - if: matrix.os == 'macos-10.15'
        name: "Notarize Macos App"
        uses: devbotsxyz/xcode-notarize@v1
        with:
          product-path: "target/Plotlyst.app"
          appstore-connect-username: ${{ secrets.NOTARIZATION_USERNAME }}
          appstore-connect-password: ${{ secrets.NOTARIZATION_PASSWORD }}
          verbose: "true"
        continue-on-error: true

      - if: matrix.os == 'macos-10.15'
        name: "Staple Macos App"
        uses: devbotsxyz/xcode-staple@v1
        with:
          product-path: "target/Plotlyst.app"

      - name: Build installer
        run: |
          fbs installer

      - uses: actions/upload-artifact@v2
        if: matrix.os == 'ubuntu-latest'
        with:
          name: app-deb-artifact
          path: target/Plotlyst.deb
      - uses: actions/upload-artifact@v2
        if: matrix.os == 'macos-10.15'
        with:
          name: app-mac-artifact
          path: target/Plotlyst.dmg
      - uses: actions/upload-artifact@v2
        if: matrix.os == 'windows-2016'
        with:
          name: app-win-artifact
          path: target\PlotlystSetup.exe
