# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build distributions

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Build_distribution:
    strategy:
      matrix:
        os: [ ubuntu-18.04, windows-2016 ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.1

      - if: matrix.os == 'ubuntu-18.04'
        name: Install fpm on Linux
        run: |
          sudo gem install --no-document fpm
      - if: matrix.os == 'macos-latest'
        name: Install fpm on Mac
        run: |
          gem install --no-document fpm
      - if: matrix.os == 'windows-2016'
        name: Install fpm on Windows
        run: |
          gem install --no-document fpm

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fbs PyQt5 overrides==3.1.0 qtwidgets PyQtChart peewee dataclasses qtawesome pyqt5ac
      - name: Generate code
        run: |
          pyqt5ac --config .pyqt5ac.yml

      - name: fbs
        run: |
          fbs freeze --debug
          fbs installer

      - uses: actions/upload-artifact@v2
        if: matrix.os == 'ubuntu-18.04'
        with:
          name: app-deb-artifact
          path: target/Plotlyst.deb
      - uses: actions/upload-artifact@v2
        if: matrix.os == 'macos-latest'
        with:
          name: app-mac-artifact
          path: target/Plotlyst.dmg
      - uses: actions/upload-artifact@v2
        if: matrix.os == 'windows-2016'
        with:
          name: app-win-artifact
          path: target\PlotlystSetup.exe
