# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build distributions

on:
  push:
    branches: [ 'feature/**' ]

jobs:
  Build_distribution:
    strategy:
      matrix:
        os: [ macos-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Add mask
        run: |
          echo "::add-mask::${{secrets.FBS_URL}}"
          echo "::add-mask::${{secrets.FBS_PROXY_URL}}"
          echo "::add-mask::${{secrets.FBS_URL_SHORTER}}"
          echo "::add-mask::${{secrets.MACOS_CERTIFICATE}}"
          echo "::add-mask::${{secrets.MACOS_CERTIFICATE_PWD}}"
          echo "::add-mask::${{secrets.KEYCHAIN_PWD}}"
          echo "::add-mask::${{secrets.NOTARIZATION_USERNAME}}"
          echo "::add-mask::${{secrets.NOTARIZATION_PASSWORD}}"
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.1

      - if: matrix.os == 'ubuntu-18.04'
        name: Install fpm on Linux
        run: |
          sudo gem install --no-document fpm
      - if: matrix.os == 'macos-latest'
        name: Install fpm on Mac
        run: |
          gem install --no-document fpm
      - if: matrix.os == 'windows-2016'
        name: Install fpm on Windows
        run: |
          gem install --no-document fpm

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gdown
          gdown ${{secrets.FBS_PROXY_URL}} -q -O fbs.tar.gz
          pip install fbs.tar.gz
          pip install pyqt5ac
          pip install -e .
      - name: Generate code
        run: |
          pyqt5ac --config .pyqt5ac.yml

      - name: fbs
        run: |
          fbs freeze

      - name: Launch
        run: |
          target/Plotlyst.app/Contents/MacOS/Plotlyst

      - if: matrix.os == 'macos-latest'
        name: Sign Macos App
        env:
          MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
          MACOS_CERTIFICATE_PWD: ${{ secrets.MACOS_CERTIFICATE_PWD }}
        run: |
          echo $MACOS_CERTIFICATE | base64 --decode > certificate.p12
          security create-keychain -p ${{secrets.KEYCHAIN_PWD}} build.keychain
          security default-keychain -s build.keychain
          security unlock-keychain -p ${{secrets.KEYCHAIN_PWD}} build.keychain
          security import certificate.p12 -k build.keychain -P $MACOS_CERTIFICATE_PWD -T /usr/bin/codesign
          security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k ${{secrets.KEYCHAIN_PWD}} build.keychain
          /usr/bin/codesign -v --timestamp --options=runtime --entitlements entitlements.plist --deep --force -s ${{secrets.MACOS_CERTIFICATE_IDENTITY}} target/Plotlyst.app

      - if: matrix.os == 'macos-latest'
        name: "Notarize Macos App"
        uses: devbotsxyz/xcode-notarize@v1
        with:
          product-path: "target/Plotlyst.app"
          appstore-connect-username: ${{ secrets.NOTARIZATION_USERNAME }}
          appstore-connect-password: ${{ secrets.NOTARIZATION_PASSWORD }}
          verbose: "true"
        continue-on-error: true

      - if: matrix.os == 'macos-latest'
        name: "Staple Macos App"
        uses: devbotsxyz/xcode-staple@v1
        with:
          product-path: "target/Plotlyst.app"

      - name: Build installer
        run: |
          fbs installer

      - uses: actions/upload-artifact@v2
        if: matrix.os == 'ubuntu-18.04'
        with:
          name: app-deb-artifact
          path: target/Plotlyst.deb
      - uses: actions/upload-artifact@v2
        if: matrix.os == 'macos-latest'
        with:
          name: app-mac-artifact
          path: target/Plotlyst.dmg
      - uses: actions/upload-artifact@v2
        if: matrix.os == 'windows-2016'
        with:
          name: app-win-artifact
          path: target\PlotlystSetup.exe
