# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Linux_build:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: |
          sudo apt-get install ruby ruby-dev rubygems build-essential
          sudo gem install --no-document fpm
          python -m pip install --upgrade pip
          pip install fbs PyQt5 overrides==3.1.0 qtwidgets PyQtChart peewee dataclasses qtawesome pyqt5ac
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Generate code
        run: |
          ./gen.sh
      - name: fbs
        run: |
          fbs freeze
          fbs installer
      - uses: actions/upload-artifact@v2
        with:
          name: app-deb-artifact
          path: target/NovelApp.deb
  Mac_build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.1
      - name: Install dependencies
        run: |
          gem install --no-document fpm
          python -m pip install --upgrade pip
          pip install fbs PyQt5 overrides==3.1.0 qtwidgets PyQtChart peewee dataclasses qtawesome pyqt5ac
      - name: Generate code
        run: |
          ./gen.sh
      - name: fbs
        run: |
          fbs freeze
          fbs installer
      - uses: actions/upload-artifact@v2
        with:
          name: app-mac-artifact
          path: target/NovelApp.dmg
  Windows_build:
    runs-on: windows-2016

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5.1
      - name: Install dependencies
        run: |
          gem install --no-document fpm
          python -m pip install --upgrade pip
          pip install fbs PyQt5 overrides==3.1.0 qtwidgets PyQtChart peewee dataclasses qtawesome pyqt5ac
      - name: Generate code
        run: |
          ./gen.sh
      - name: fbs
        run: |
          fbs freeze
          fbs installer
      - uses: actions/upload-artifact@v2
        with:
          name: app-win-artifact
          path: target\NovelAppSetup.exe
