name: Test

on: [ push ]

jobs:
  gui_test:
    runs-on: ubuntu-22.04

    steps:
      - name: Add mask
        run: |
          echo "::add-mask::${{secrets.FBS_URL}}"
          echo "::add-mask::${{secrets.FBS_PROXY_URL}}"
          echo "::add-mask::${{secrets.FBS_URL_SHORTER}}"
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.18
      - name: Prepare GUI tests
        run: |
          sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils
          /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
          sudo apt update
          sudo apt install -y libpulse-mainloop-glib0 libegl1-mesa-dev libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev libunwind-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest-xvfb
          pip install gdown
          gdown ${{secrets.FBS_PROXY_URL}} -q -O fbs.tar.gz
          pip install fbs.tar.gz
          pip install -e .[test]
          pip install git+https://github.com/plotlyst/qt-uic.git
          pip install git+https://github.com/plotlyst/qt-menu.git
          pip install git+https://github.com/plotlyst/qt-tour.git
          pip install git+https://github.com/plotlyst/qt-anim.git
          pip install git+https://github.com/plotlyst/qt-textedit.git
          pip install git+https://github.com/plotlyst/qt-emojipicker.git
          pip install git+https://github.com/plotlyst/qt-frames.git
          pip install git+https://github.com/plotlyst/qt-toolbox-widget.git
          pip install git+https://github.com/plotlyst/language_tool_python.git@plotlyst
      - name: Test with pytest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISPLAY: ':99.0'
        run: |
          ./test.sh

  core-windows-test:
    runs-on: windows-2019
    steps:
      - name: Add mask
        run: |
          echo "::add-mask::${{secrets.FBS_URL}}"
          echo "::add-mask::${{secrets.FBS_PROXY_URL}}"
          echo "::add-mask::${{secrets.FBS_URL_SHORTER}}"
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install gdown
          gdown ${{secrets.FBS_PROXY_URL}} -q -O fbs.tar.gz
          pip install fbs.tar.gz
          pip install -e .[test]
          pip install git+https://github.com/plotlyst/qt-uic.git
          pip install git+https://github.com/plotlyst/qt-menu.git
          pip install git+https://github.com/plotlyst/qt-tour.git
          pip install git+https://github.com/plotlyst/qt-anim.git
          pip install git+https://github.com/plotlyst/qt-textedit.git
          pip install git+https://github.com/plotlyst/qt-emojipicker.git
          pip install git+https://github.com/plotlyst/qt-frames.git
          pip install git+https://github.com/plotlyst/qt-toolbox-widget.git
          pip install git+https://github.com/plotlyst/language_tool_python.git@plotlyst
      - name: Set PYTHONPATH
        run: |
          echo "PYTHONPATH=src/main/python" >> "$GITHUB_ENV"
      - name: Test with pytest
        run: |
          python uic_gen.py
          python -m pytest src/main/python/plotlyst/test/core --cov-report term -v --color=yes

  
