name: Test

on: [ push ]

jobs:
  gui_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Prepare GUI tests
        run: |
          sudo apt install libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0
                  /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
          sudo apt install -y libpulse-mainloop-glib0
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest-xvfb
          pip install -e .[test]
      - name: Test with pytest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./gen.sh
          ./test.sh
          pip install coveralls
          coveralls --service=github

  core-windows-test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Test with pytest
        run: |
          pyuic6 ui/about_dialog.ui -o src/main/python/plotlyst/view/generated/about_dialog_ui.py
          pyuic6 ui/avatar_widget.ui -o src/main/python/plotlyst/view/generated/avatar_widget.ui.py
          pyuic6 ui/backstory_editor_dialog.ui -o src/main/python/plotlyst/view/generated/backstory_editor_dialog.ui.py
          pyuic6 ui/cause_and_effect_editor.ui -o src/main/python/plotlyst/view/generated/cause_and_effect_editor.ui.py
          pyuic6 ui/character_backstory_card.ui -o src/main/python/plotlyst/view/generated/character_backstory_card.ui.py
          pyuic6 ui/character_card.ui -o src/main/python/plotlyst/view/generated/character_card.ui.py
          pyuic6 ui/character_conflict_widget.ui -o src/main/python/plotlyst/view/generated/character_conflict_widget.ui.py
          pyuic6 ui/character_editor.ui -o src/main/python/plotlyst/view/generated/character_editor.ui.py
          pyuic6 ui/character_profile_editor_dialog.ui -o src/main/python/plotlyst/view/generated/character_profile_editor_dialog.ui.py
          pyuic6 ui/characters_view.ui -o src/main/python/plotlyst/view/generated/characters_view.ui.py
          pyuic6 ui/comments_view.ui -o src/main/python/plotlyst/view/generated/comments_view.ui.py
          pyuic6 ui/comment_widget.ui -o src/main/python/plotlyst/view/generated/comment_widget.ui.py
          pyuic6 ui/directory_picker_dialog.ui -o src/main/python/plotlyst/view/generated/directory_picker_dialog.ui.py
          pyuic6 ui/docs_sidebar_widget.ui -o src/main/python/plotlyst/view/generated/docs_sidebar_widget.ui.py
          pyuic6 ui/field_text_selection_widget.ui -o src/main/python/plotlyst/view/generated/field_text_selection_widget.ui.py
          pyuic6 ui/home_view.ui -o src/main/python/plotlyst/view/generated/home_view.ui.py
          pyuic6 ui/icon_selector_widget.ui -o src/main/python/plotlyst/view/generated/icon_selector_widget.ui.py
          pyuic6 ui/items_editor_dialog.ui -o src/main/python/plotlyst/view/generated/items_editor_dialog.ui.py
          pyuic6 ui/items_editor_widget.ui -o src/main/python/plotlyst/view/generated/items_editor_widget.ui.py
          pyuic6 ui/journal_card.ui -o src/main/python/plotlyst/view/generated/journal_card.ui.py
          pyuic6 ui/journal_widget.ui -o src/main/python/plotlyst/view/generated/journal_widget.ui.py
          pyuic6 ui/locations_view.ui -o src/main/python/plotlyst/view/generated/locations_view.ui.py
          pyuic6 ui/main_window.ui -o src/main/python/plotlyst/view/generated/main_window.ui.py
          pyuic6 ui/manuscript_view.ui -o src/main/python/plotlyst/view/generated/manuscript_view.ui.py
          pyuic6 ui/notes_view.ui -o src/main/python/plotlyst/view/generated/notes_view.ui.py
          pyuic6 ui/novel_card.ui -o src/main/python/plotlyst/view/generated/novel_card.ui.py
          pyuic6 ui/novel_creation_dialog.ui -o src/main/python/plotlyst/view/generated/novel_creation_dialog.ui.py
          pyuic6 ui/novel_view.ui -o src/main/python/plotlyst/view/generated/novel_view.ui.py
          pyuic6 ui/plot_editor_dialog.ui -o src/main/python/plotlyst/view/generated/plot_editor_dialog.ui.py
          pyuic6 ui/reports_view.ui -o src/main/python/plotlyst/view/generated/reports_view.ui.py
          pyuic6 ui/scene_beat_item_widget.ui -o src/main/python/plotlyst/view/generated/scene_beat_item_widget.ui.py
          pyuic6 ui/scene_builder_preview_dialog.ui -o src/main/python/plotlyst/view/generated/scene_builder_preview_dialog.ui.py
          pyuic6 ui/scene_card.ui -o src/main/python/plotlyst/view/generated/scene_card.ui.py
          pyuic6 ui/scene_dstribution_widget.ui -o src/main/python/plotlyst/view/generated/scene_dstribution_widget.ui.py
          pyuic6 ui/scene_editor.ui -o src/main/python/plotlyst/view/generated/scene_editor.ui.py
          pyuic6 ui/scene_element_edition_dialog.ui -o src/main/python/plotlyst/view/generated/scene_element_edition_dialog.ui.py
          pyuic6 ui/scene_filter_widget.ui -o src/main/python/plotlyst/view/generated/scene_filter_widget.ui.py
          pyuic6 ui/scene_ouctome_selector.ui -o src/main/python/plotlyst/view/generated/scene_ouctome_selector.ui.py
          pyuic6 ui/scene_structure_editor_widget.ui -o src/main/python/plotlyst/view/generated/scene_structure_editor_widget.ui.py
          pyuic6 ui/scenes_view.ui -o src/main/python/plotlyst/view/generated/scenes_view.ui.py
          pyuic6 ui/sprint_widget.ui -o src/main/python/plotlyst/view/generated/sprint_widget.ui.py
          pyuic6 ui/tasks_widget.ui -o src/main/python/plotlyst/view/generated/tasks_widget.ui.py
          pyuic6 ui/timeline_view.ui -o src/main/python/plotlyst/view/generated/timeline_view.ui.py
          pyuic6 ui/timer_setup_widget.ui -o src/main/python/plotlyst/view/generated/timer_setup_widget.ui.py

          python -m pytest src/main/python/plotlyst/test/core --cov-report term -v --color=yes

  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 src/main/python/plotlyst --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 src/main/python/plotlyst --count --statistics
  
